name: ubuntu-package-status
version: '0.0.3'
base: core18
summary: Fetch package version data for specified packages in the Ubuntu archive
description: |
  Helpful utility to fetch package version data for specified packages in the Ubuntu archive.

  Similar to [rmadison](http://manpages.ubuntu.com/manpages/focal/man1/rmadison.1.html) utility
  or the [rmadison webpage](https://people.canonical.com/~ubuntu-archive/madison.cgi) but allows for querying
  multiple packages at the same time and also support TXT, JSON and CSV output formats.

  This makes it easy to use with other tools - like a monitoring tool which is my use case.

  # Usage:
  `ubuntu-package-status --help` Shows all available options and their expected values
  `ubuntu-package-status --config-skeleton` Shows the format of the expected yaml config

  ```
  ubuntu-package-status
         --config="config.yaml"
         --logging-level=DEBUG
         --output-format=CSV > "package-stats.csv"
  ```

  This will write the current state of your packages in the archive to a "package-stats.csv" fi

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  ubuntu-package-status:
    environment:
      PATH: "$SNAP/usr/bin:$SNAP/bin/:$PATH"
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
    command: bin/snapcraft-preload $SNAP/bin/ubuntu-package-status
    plugs:
      - network
      - home

parts:
  ubuntu-package-status:
    plugin: python
    requirements:
      - src/requirements.txt
    source: .
    stage-packages:
      - python3-launchpadlib
  snapcraft-preload:
    source: https://github.com/diddledan/snapcraft-preload.git
    source-branch: semaphore-support
    plugin: cmake
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib

